#
#
#
#
#
# LOCAL VERSION
#
#
#
#
#
#
version: '2'
services:
    nginx:
        build: ./proxy
        container_name: nginx
        ports:
          - "80:80"
        volumes:
          - basedata:/etc/nginx/conf.d
        networks:
            - appnet
    #nginx gen
    # nginx-gen:
    #     image: jwilder/docker-gen:latest
    #     container_name: nginx-gen
    #     command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    #     volumes_from:
    #         - nginx
    #     volumes:
    #         - /var/run/docker.sock:/tmp/docker.sock:ro
    #         - ./docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    #     networks:
    #         - appnet
# used for interal communication within docker
networks:
    appnet:
        driver: "bridge"
# used to store and persist data
volumes:
    basedata:
        driver: "local"
