#
#
#
#
#
# LOCAL VERSION
#
#
#
#
#
#
version: '2'
services:
    nginx:
        build: ./proxy
        container_name: nginx
        ports:
          - "80:80"
        volumes:
          - /etc/nginx/conf.d
          - ./proxy/includes/proxy.conf:/etc/nginx/proxy.conf
          - ./proxy/includes/catch.conf:/etc/nginx/catch.conf
          - ./proxy/includes/ssl-params.conf:/etc/nginx/ssl-params.conf
        networks:
            - appnet
    #nginx gen
    # nginx-gen:
    #     image: jwilder/docker-gen:latest
    #     container_name: nginx-gen
    #     command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    #     volumes_from:
    #         - nginx
    #     volumes:
    #         - /var/run/docker.sock:/tmp/docker.sock:ro
    #         - ./docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    #     networks:
    #         - appnet
# used for interal communication within docker
networks:
    appnet:
        driver: "bridge"
