version: '2'
services:
    nginx:
        image: nginx:alpine # using alpine for newer openssl for http2 with ALPAN
        container_name: nginx
        volumes:
            - /var/www/html
            - ./logs/nginx/:/var/log/nginx:rw
            - ./nginx/includes:/etc/nginx/includes:ro
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ../letsencrypt/:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        restart: always # makes container restart on server restart
        networks:
            - appnet
# used for interal communication within docker
networks:
    appnet:
        driver: "bridge"
# used to store and persist data
volumes:
    letsencrypt:
        driver: "local"
    apps:
         driver: "local"
