version: '2'
services:
    nginx:
        build: ./nginx
        volumes_from: [php]
        volumes:
            - ./nginx/default:/etc/nginx/sites-enabled/default
        networks:
            - fsdocker_appnet
        depends_on:
            - php
            - db
            - redis
    # php
    php:
        build: ./php
        container_name: cms_php
        volumes:
            - ../../apps/cms/:/var/www/html/
        networks:
            - fsdocker_appnet
    # session & cache
    redis:
        container_name: cms_redis
        image: redis:alpine
        networks:
            - fsdocker_appnet
    # mysql db
    db:
        image: mysql:latest
        container_name: cms_db
        ports:
            - "3302:3306"
        command: mysqld --performance_schema=0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: formandsystem_cms
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - cmsdata:/var/lib/mysql
        networks:
            - fsdocker_appnet
# used for interal communication within docker
networks:
    fsdocker_appnet:
        external: true
# used to store and persist data
volumes:
    cmsdata:
        driver: "local"
